# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [2]:
array = np.array([10, 20, 30, 40, 50])
value = 27

# Compute the absolute differences
differences = np.abs(array - value)

# Find the index of the minimum difference
index = np.argmin(differences)

# Get the nearest value
nearest_value = array[index]

print(nearest_value)  


30


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [9]:
A = np.arange(3).reshape(1, 3)  # Shape (1,3)
B = np.arange(3).reshape(3, 1)  # Shape (3,1)

# Using an iterator to sum elements
it = np.nditer([A, B, None])  # 'None' will store the result
for x, y, z in it:
    z[...] = x + y  # Store the sum in z
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [3]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="default"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __repr__(self):
        return f"NamedArray(name={self.name}, array={super().__repr__()})"

arr = NamedArray([1, 2, 3], name="MyArray")
print(arr)


[1 2 3]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [4]:
Z = np.zeros(10)  # Vector of zeros
indices = np.array([1, 3, 3, 5, 3])  # Indices where we add 1

np.add.at(Z, indices, 1)  # Add 1 at specified positions

print(Z)


[0. 1. 0. 3. 0. 1. 0. 0. 0. 0.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [5]:
X = np.array([1, 2, 3, 4, 5])  # Values to accumulate
I = np.array([0, 1, 2, 1, 2])  # Indices in F
F = np.zeros(3)  # Output array

np.add.at(F, I, X)  # Accumulate values in F

print(F) 


[1. 6. 8.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [6]:
import numpy as np

w, h = 256, 256
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)  # Ensure correct syntax

# Reshape the image to a 2D array where each row is a color (RGB triplet)
colors = image.reshape(-1, 3)

# Find unique colors
unique_colors = np.unique(colors, axis=0)

print(len(unique_colors))  # Number of unique colors in the image


65407


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [7]:
A = np.random.rand(3, 4, 5, 6)  # Example 4D array
result = A.sum(axis=(-2, -1))  # Sum over last two axes

print(result.shape)  


(3, 4)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [8]:

import numpy as np

D = np.random.randint(0, 10, 10)  # Random vector
S = np.random.randint(0, 3, 10)   # Subset indices (3 subsets)

means = np.bincount(S, weights=D) / np.bincount(S)
print(means)




[4.2 nan 3.6]


C:\Users\Admin\AppData\Local\Temp\ipykernel_15632\2094621257.py:6: RuntimeWarning: invalid value encountered in divide
  means = np.bincount(S, weights=D) / np.bincount(S)


#### 69. How to get the diagonal of a dot product? (★★★)

In [9]:
A = np.random.randint(0, 10, (4, 4))
B = np.random.randint(0, 10, (4, 4))

diagonal = np.einsum("ij,ji->i", A, B)
print(diagonal)


[60 64  8 88]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [11]:
Z = np.array([1, 2, 3, 4, 5])
new_Z = np.zeros(len(Z) + (len(Z) - 1) * 3, dtype=int)
new_Z[::4] = Z
print(new_Z)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [12]:
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)

result = A * B[:, :, None]  # Expanding B to match A's dimensions
print(result.shape)


(5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [13]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]  # Swap row 0 and row 1
print(A)


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [14]:
triangles = np.random.randint(0, 20, (10, 3))
edges = np.sort(np.array([(a, b) for t in triangles for a, b in zip(t, np.roll(t, 1))]), axis=1)
unique_edges = np.unique(edges, axis=0)
print(unique_edges)


[[ 0  8]
 [ 0 14]
 [ 2  3]
 [ 2 11]
 [ 3  4]
 [ 3  8]
 [ 3 11]
 [ 3 12]
 [ 3 18]
 [ 4  9]
 [ 4 12]
 [ 4 13]
 [ 5 14]
 [ 5 19]
 [ 8 14]
 [ 8 18]
 [ 9 12]
 [ 9 13]
 [ 9 15]
 [12 14]
 [12 15]
 [12 16]
 [13 15]
 [13 16]
 [14 16]
 [14 19]
 [15 16]
 [15 17]
 [15 18]
 [17 18]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [15]:
C = np.array([2, 3, 0, 1])
A = np.repeat(np.arange(len(C)), C)
print(A)


[0 0 1 1 1 3]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [16]:
Z = np.arange(10)
window_size = 3
mean_Z = np.convolve(Z, np.ones(window_size)/window_size, mode='valid')
print(mean_Z)


[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [17]:
Z = np.arange(10)
window = 3
shape = (Z.size - window + 1, window)
strides = (Z.strides[0], Z.strides[0])

result = np.lib.stride_tricks.as_strided(Z, shape=shape, strides=strides)
print(result)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [18]:
Z = np.array([True, False, True])
Z = ~Z  # Boolean negation
print(Z)

F = np.array([1.0, -2.5, 3.4])
F *= -1  # In-place negation
print(F)


[False  True False]
[-1.   2.5 -3.4]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [19]:
P0 = np.random.rand(5, 2)
P1 = np.random.rand(5, 2)
p = np.random.rand(2)

line_vec = P1 - P0
point_vec = P0 - p
proj = np.sum(point_vec * line_vec, axis=1) / np.sum(line_vec ** 2, axis=1)
nearest = P0 + proj[:, None] * line_vec
dist = np.linalg.norm(nearest - p, axis=1)
print(dist)


[0.83947023 0.86750271 0.45553242 0.31795576 1.02435841]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [20]:
P = np.random.rand(10, 2)  # 10 points
distances = np.array([np.linalg.norm((P0 + ((np.sum((P - P0) * (P1 - P0), axis=1) / np.sum((P1 - P0) ** 2, axis=1))[:, None] * (P1 - P0))) - P, axis=1) for P in P])
print(distances)


[[0.2118311  0.39352739 0.02601151 0.126288   0.05264106]
 [0.42956368 0.6800144  0.33329266 0.3648502  0.03647149]
 [0.26300392 0.02407694 0.10942126 0.54843072 0.50412062]
 [0.15764545 0.05685573 0.22582319 0.27318016 0.23586086]
 [0.3858354  0.58166941 0.14922483 0.16631517 0.101473  ]
 [0.28684308 0.07520743 0.33500759 0.27162859 0.29456882]
 [0.10798114 0.29078556 0.1044196  0.13763252 0.00458444]
 [0.2420805  0.539371   0.31470095 0.5508319  0.27168743]
 [0.03821564 0.10858307 0.31781477 0.01494839 0.02536362]
 [0.21881776 0.12022927 0.59166105 0.15037913 0.07333541]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [21]:
def extract_subarray(arr, center, shape, fill_value=0):
    out = np.full(shape, fill_value, dtype=arr.dtype)
    slices = tuple(slice(max(c - s//2, 0), min(c - s//2 + s, arr.shape[i])) for i, (c, s) in enumerate(zip(center, shape)))
    out_slices = tuple(slice(0, s.stop - s.start) for s in slices)
    out[out_slices] = arr[slices]
    return out

A = np.random.randint(0, 10, (10, 10))
print(extract_subarray(A, (5, 5), (5, 5), fill_value=-1))


[[8 2 6 8 2]
 [7 3 5 2 9]
 [0 6 2 8 3]
 [3 6 1 7 1]
 [3 6 8 7 1]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [22]:
Z = np.arange(1, 15)
R = np.lib.stride_tricks.sliding_window_view(Z, 4)
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [23]:
A = np.random.rand(5, 5)
rank = np.linalg.matrix_rank(A)
print(rank)


5


#### 83. How to find the most frequent value in an array?

In [24]:
Z = np.random.randint(0, 10, 100)
most_frequent = np.bincount(Z).argmax()
print(most_frequent)


0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [25]:
A = np.random.randint(0, 10, (10, 10))
blocks = np.lib.stride_tricks.sliding_window_view(A, (3, 3))
print(blocks.shape)


(8, 8, 3, 3)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [26]:
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        super().__setitem__((index[1], index[0]), value)
        super().__setitem__(index, value)

Z = np.zeros((5, 5)).view(SymmetricArray)
Z[1, 2] = 5
print(Z)


[[0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
def sum_matrix_products(matrices, vectors):
    return np.einsum('ijk,ik->j', matrices, vectors)
sum_matrix_products


<function __main__.sum_matrix_products(matrices, vectors)>

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [32]:
Z = np.random.rand(16, 16)
block_sum = Z.reshape(4, 4, 4, 4).sum(axis=(1, 3))
print(block_sum)


[[8.36998912 7.81080048 8.47353375 6.83723513]
 [7.59475147 9.38445736 7.71378964 6.05543306]
 [8.95674409 8.19553674 7.09527617 7.92720671]
 [8.75945811 8.02004987 8.41200202 7.79073277]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [35]:
def game_of_life_step(Z):
    neighbors = sum(np.roll(np.roll(Z, i, 0), j, 1)
                    for i in (-1, 0, 1) for j in (-1, 0, 1) if (i, j) != (0, 0))
    return (neighbors == 3) | (Z & (neighbors == 2))

#### 89. How to get the n largest values of an array (★★★)

In [37]:
# 89. Get n largest values of an array
Z = np.random.rand(10)
n_largest = Z[np.argpartition(Z, -5)[-5:]]
n_largest

array([0.76160375, 0.80028966, 0.8199154 , 0.88208389, 0.99114587])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [40]:
# 90. Compute Cartesian product of multiple vectors
from itertools import product
def cartesian_product(*arrays):
    return np.array(list(product(*arrays)))


#### 91. How to create a record array from a regular array? (★★★)

In [41]:
def to_record_array(array, dtype):
    return np.array(list(map(tuple, array)), dtype=dtype)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [43]:
# 92. Compute Z^3 using 3 different methods
Z = np.random.rand(10000)
z3_methods = [Z**3, np.power(Z, 3), np.einsum('i,i,i->i', Z, Z, Z)]
z3_methods

[array([0.93110054, 0.33062667, 0.47920627, ..., 0.1471123 , 0.11071914,
        0.00339914], shape=(10000,)),
 array([0.93110054, 0.33062667, 0.47920627, ..., 0.1471123 , 0.11071914,
        0.00339914], shape=(10000,)),
 array([0.93110054, 0.33062667, 0.47920627, ..., 0.1471123 , 0.11071914,
        0.00339914], shape=(10000,))]

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [2]:
# 93. Find rows of A containing elements of each row of B
import numpy as np
A = np.random.randint(0, 10, (8, 3))
B = np.random.randint(0, 10, (2, 2))
mask = np.array([np.all(np.isin(B[i], A), axis=0) for i in range(B.shape[0])])
matching_rows = A[np.any(mask, axis=0)]

In [3]:
matching_rows

array([[[3, 4, 6],
        [3, 5, 6],
        [2, 6, 6],
        [5, 4, 8],
        [4, 9, 6],
        [4, 0, 8],
        [9, 2, 7],
        [9, 9, 7]]], dtype=int32)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [46]:
# 94. Extract rows with unequal values
Z = np.random.randint(0, 5, (10, 3))
unique_rows = Z[(Z[:, 0] != Z[:, 1]) | (Z[:, 1] != Z[:, 2])]
unique_rows


array([[2, 0, 0],
       [2, 0, 3],
       [3, 2, 1],
       [1, 2, 1],
       [1, 3, 3],
       [0, 1, 2],
       [0, 3, 1],
       [1, 4, 0],
       [1, 2, 0],
       [1, 3, 1]], dtype=int32)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [48]:
V = np.array([1, 2, 3, 4, 5])
binary_matrix = ((V[:, None] & (1 << np.arange(8))) > 0).astype(int)
binary_matrix

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0]])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [49]:
Z = np.random.randint(0, 5, (10, 3))
unique_Z = np.unique(Z, axis=0)
unique_Z

array([[0, 2, 0],
       [0, 3, 3],
       [1, 0, 3],
       [1, 1, 3],
       [1, 3, 4],
       [3, 0, 1],
       [4, 1, 1],
       [4, 1, 3],
       [4, 4, 2]], dtype=int32)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [51]:
A, B = np.random.rand(5), np.random.rand(5)
inner = np.einsum('i,i->', A, B)
outer = np.einsum('i,j->ij', A, B)
sum_all = np.einsum('i->', A)
mul = np.einsum('i,i->i', A, B)
A,B

(array([0.33698874, 0.70435604, 0.31443026, 0.49594046, 0.6533659 ]),
 array([0.79886128, 0.31690803, 0.27177694, 0.28022672, 0.03613072]))

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [55]:
X, Y = np.random.rand(10), np.random.rand(10)
from scipy.interpolate import interp1d
interp_func = interp1d(np.linspace(0, 1, len(X)), np.c_[X, Y], kind='linear', axis=0)
sampled_points = interp_func(np.linspace(0, 1, 20))
sampled_points

array([[0.28142877, 0.66483953],
       [0.37915647, 0.60945936],
       [0.47688417, 0.55407918],
       [0.49581011, 0.49825895],
       [0.50488583, 0.4423837 ],
       [0.61912299, 0.55197172],
       [0.76340629, 0.70883496],
       [0.66648478, 0.64138137],
       [0.44896089, 0.46176935],
       [0.34318699, 0.4602722 ],
       [0.32681311, 0.60126694],
       [0.28590723, 0.74066394],
       [0.21433637, 0.87806378],
       [0.29289834, 0.87268851],
       [0.67172601, 0.58176304],
       [0.94576412, 0.32518425],
       [0.85303878, 0.18881883],
       [0.75698424, 0.10648244],
       [0.63429613, 0.45637838],
       [0.51160802, 0.80627431]])

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [56]:
X = np.random.randint(0, 4, (10, 5))
n = 5
valid_rows = X[np.all(X >= 0, axis=1) & (X.sum(axis=1) == n)]
valid_rows

array([[0, 2, 0, 0, 3]], dtype=int32)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [57]:
X = np.random.rand(1000)
N = 1000
means = np.random.choice(X, (N, len(X)), replace=True).mean(axis=1)
conf_intervals = np.percentile(means, [2.5, 97.5])
conf_intervals

array([0.48060094, 0.51535506])