In [1]:
# Numpy Exercise 1
# 1. Import the numpy package under the name `np`

import numpy as np

In [3]:
# 2. Print the numpy version and the configuration 
print(np.__version__)
print(np.show_config())

2.2.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-fwtr2gmz/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-fwtr2gmz/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-fwtr2gmz/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-fwtr2gmz/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

In [6]:
# 3. Create a null vector of size 10 
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:

# 4. How to find the memory size of any array 
print(f"Memory size: {arr.size * arr.itemsize} bytes")

Memory size: 80 bytes


In [8]:
# 5. How to get the documentation of the numpy add function from the command line? 

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [9]:
# 6. Create a null vector of size 10 but the fifth value is 1 
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
# 7. Create a vector with values ranging from 10 to 49 
vec = np.arange(10, 50)
print(vec)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
# 8. Reverse a vector (first element becomes last) 
vec_reversed = vec[::-1]
print(vec_reversed)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [12]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 
mat = np.arange(9).reshape(3, 3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] 
arr = np.array([1, 2, 0, 0, 4, 0])
nz_indices = np.nonzero(arr)
print(nz_indices)


(array([0, 1, 4]),)


In [14]:
# 11. Create a 3x3 identity matrix 
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# 12. Create a 3x3x3 array with random values 
random_array = np.random.randint(0,101,size=(3, 3, 3))
print(random_array)

[[[67 99 84]
  [44  5 39]
  [18 80 74]]

 [[57  0 62]
  [56 21 55]
  [38 25 90]]

 [[50 64 56]
  [74  2 83]
  [86 10 98]]]


In [28]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 
rand_matrix = np.random.randint(10,51,size=(10, 10))
min_val = rand_matrix.min()
max_val = rand_matrix.max()
print(rand_matrix)
print(f"Min is: {min_val}, Max is: {max_val}")

[[29 24 15 40 14 46 46 33 50 25]
 [14 35 21 28 42 25 14 45 13 18]
 [29 43 45 41 45 37 47 30 13 48]
 [36 39 19 22 24 47 48 45 12 23]
 [16 31 45 22 17 41 48 43 37 42]
 [47 10 39 10 10 17 15 12 10 40]
 [48 29 39 24 12 46 37 25 24 45]
 [32 36 46 42 16 20 50 38 15 36]
 [41 47 48 12 50 17 46 17 15 20]
 [47 50 40 19 12 40 49 18 36 24]]
Min is: 10, Max is: 50


In [29]:
# 14. Create a random vector of size 30 and find the mean value 
rand_vec = np.random.randint(0,50,size=30)
mean_val = rand_vec.mean()
print(rand_vec)
print(f"Mean: {mean_val}")

[21 20 23  1 37 31 25 18  5  9 28 22 23 10 43 47 34 20 44 41 42 48 16 37
  7 35 42 46 27 41]
Mean: 28.1


In [30]:
# 15. Create a 2D array with 1 on the border and 0 inside 
array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
