In [1]:
# 31. How to ignore all NumPy warnings (not recommended)?
import numpy as np
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")

# Another way using numpy
np.seterr(all='ignore')


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [2]:
# 32. Is the following expression true?
import numpy as np

print(np.sqrt(-1) == np.emath.sqrt(-1))


False


np.sqrt(-1) results in nan (Not a Number) because the standard NumPy square root function only works with real numbers.
np.emath.sqrt(-1) correctly computes the square root in the complex number domain and returns 1j (imaginary unit).
Since nan is not equal to 1j, the result is False.

In [3]:
# 33. How to get the dates of yesterday, today, and tomorrow?
import numpy as np
import datetime

today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2025-02-16
Today: 2025-02-17
Tomorrow: 2025-02-18


In [4]:
# 34. How to get all the dates corresponding to the month of July 2016?
july_dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july_dates)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?


A = np.array([1, 2, 3], dtype=float) 
B = np.array([4, 5, 6])

A += B 
A *= -A / 2  
print(A)


[-12.5 -24.5 -40.5]


In [7]:
# 36. Extract the integer part of a random array using 4 methods
Z = np.random.uniform(0, 10, 10)

print(Z - Z % 1)  
print(np.floor(Z)) 
print(np.trunc(Z))  
print(Z.astype(int))  


[9. 4. 1. 8. 0. 2. 7. 2. 3. 3.]
[9. 4. 1. 8. 0. 2. 7. 2. 3. 3.]
[9. 4. 1. 8. 0. 2. 7. 2. 3. 3.]
[9 4 1 8 0 2 7 2 3 3]


In [8]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4

Z = np.tile(np.arange(5), (5, 1))
print(Z)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [9]:
# 38. Generator function that generates 10 integers and use it to build an array

def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(), dtype=int)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

Z = np.random.uniform(0, 1, 10)
print(Z)


[0.85172452 0.04140565 0.80287337 0.90002263 0.93629484 0.6344594
 0.87040131 0.86310709 0.67569085 0.93966112]


In [14]:
# 40. Create a random vector of size 10 and sort it

Z = np.random.randint(0,101,size=(10))
Z.sort()
print(Z)

[ 0  4  9 13 27 49 64 73 75 90]


In [15]:
# 41. How to sum a small array faster than np.sum?

Z = np.random.randint(0,50,size=(10))

result = np.add.reduce(Z)
print(result)

209


In [26]:
# 42. Check if two random arrays A and B are equal

A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print(A)
print(B)


equal = np.array_equal(A, B)
print(equal)

[1 1 1 0 0]
[1 1 0 0 0]
False


In [17]:
# 43. Make an array immutable (read-only)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1 

ValueError: assignment destination is read-only

In [21]:
# 44. Convert a 10x2 matrix from Cartesian to polar coordinates

Z = np.random.rand(10, 2)
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)
Theta = np.arctan2(Y, X)

print(R, Theta)

[1.02348904 1.04362667 0.48649131 1.02679003 0.66213134 0.99817549
 0.7479322  0.12673955 0.43575028 0.82227619] [0.74575568 0.3192588  0.3831854  0.61173926 0.82821149 0.9090599
 0.65787267 0.34635572 1.30517397 0.56524371]


In [22]:
# 45. Replace the maximum value in a random vector with 0

Z = np.random.rand(10)
Z[Z.argmax()] = 0
print(Z)

[0.10651276 0.         0.69670221 0.35704742 0.3032592  0.66535135
 0.46757927 0.85232193 0.07522813 0.35896583]
