In [2]:
#Exercise 16: Add a border (filled with 0's) around an existing array
import numpy as np

array = np.ones((3, 3))  # Create a 3x3 matrix filled with 1s
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Exercise 17: What is the result of the following expressions?
0 * np.nan    


nan

In [12]:
np.nan == np.nan   


False

In [7]:
np.inf > np.nan    


False

In [8]:
np.nan - np.nan    


nan

In [10]:
np.nan in set([np.nan]) 


True

In [11]:
0.3 == 3 * 0.

False

0 * np.nan results in NaN because any operation with NaN is undefined.
np.nan == np.nan is False because NaN is not equal to anything, not even itself.
np.inf > np.nan is False since NaN is not comparable.
np.nan - np.nan is NaN, again because operations with NaN are undefined.
np.nan in set([np.nan]) is True because Python's set can store NaN as a unique element.
0.3 == 3 * 0.1 is False due to floating-point precision errors.

In [13]:
# Exercise 18: Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix = np.diag([1, 2, 3, 4], k=-1)
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [14]:
# Exercise 19: Create an 8x8 checkerboard matrix
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Set 1 in every alternate row
checkerboard[::2, 1::2] = 1  # Set 1 in every alternate column
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [15]:
# Exercise 20: Index of the 100th element in a (6,7,8) shape array
index = np.unravel_index(100, (6, 7, 8))
print(index)  


(np.int64(1), np.int64(5), np.int64(4))


In [16]:
# Exercise 21: Create a checkerboard using tile()
pattern = np.array([[0, 1], [1, 0]])  # 2x2 checkerboard base pattern
checkerboard = np.tile(pattern, (4, 4))  # Repeat 4x4 times
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
# Exercise 22: Normalize a 5x5 random matrix
matrix = np.random.random((5, 5))  # Random 5x5 matrix
normalized = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print(normalized)


[[0.8248751  0.28020234 0.70011201 0.22303142 0.38415957]
 [0.43757759 0.55830197 0.99076153 0.57061395 1.        ]
 [0.94688947 0.82273268 0.38377929 0.77230393 0.08255455]
 [0.5916354  0.39705905 0.8791334  0.51597131 0.60380774]
 [0.75653662 0.9600448  0.2811441  0.21138605 0.        ]]


In [18]:
# Exercise 24: Multiply a 5x3 matrix by a 3x2 matrix
A = np.random.randint(1, 10, (5, 3))  # 5x3 matrix
B = np.random.randint(1, 10, (3, 2))  # 3x2 matrix
C = np.dot(A, B)  # Matrix multiplication
print(C)


[[39 49]
 [54 64]
 [75 53]
 [81 75]
 [54 88]]
